routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
| 
| php artisan vendor:publish --tag=laravel-pagination
|
*/

Route::get('/', 'QuestionsController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('questions', 'QuestionsController')->except('show');
Route::resource('questions.answers', 'AnswersController')->only(['store', 'edit', 'update', 'destroy']);
Route::get('/questions/{slug}', 'QuestionsController@show')->name('questions.show');
Route::post('/answers/{answer}/accept', 'AcceptAnswerController')->name('answers.accept');

Route::post('/questions/{question}/favorites', 'FavoritesController@store')->name('questions.favorite');
Route::delete('/questions/{question}/favorites', 'FavoritesController@destroy')->name('questions.unfavorite');

Route::post('/questions/{question}/vote', 'VoteQuestionController')->name('question.vote');
Route::post('/answers/{answer}/vote', 'VoteAnswerController')->name('answer.vote');

app/Answer.php
<?php

namespace App;

use App\Traits\Votable;
use Illuminate\Database\Eloquent\Model;

class Answer extends Model
{
    use Votable;

    protected $fillable = [
        'body',
        'user_id'
    ];

    public function question()
    {
        return $this->belongsTo(Question::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
    
    public static function boot()
    {
        parent::boot();
    
        static::created(function($answer) {
            $answer->question->increment('answer_count');
        });

        static::deleted(function($answer) {
            $answer->question->decrement('answer_count');
        });
    }

    public function getBodyHtmlAttribute()
    {
        return clean(\Parsedown::instance()->text($this->body));
    }

    public function getCreatedDateAttribute()
    {
        return $this->created_at->diffForHumans();
    }

    public function getStatusAttribute()
    {
        return $this->isBest() ? 'vote-accepted' : '';
    }

    public function getIsBestAttribute()
    {
        return $this->isBest();
    }

    public function isBest()
    {
        return $this->id === $this->question->best_answer_id ? 'vote-accepted' : '';
    }
}

app/Question.php
<?php

namespace App;

use App\Traits\Votable;
use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    use Votable;

    protected $fillable = [
        'title',
        'body'
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function answers()
    {
        return $this->hasMany(Answer::class)->orderBy('vote_count', 'DESC');
    }

    public function favorites()
    {
        return $this->belongsToMany(User::class, 'favorites')->withTimestamps(); //'question_id', 'user_id'
    }

    public function setTitleAttribute($value)
    {
        $this->attributes['title'] = $value;
        $this->attributes['slug'] = str_slug($value);
    }

    // Accessor fo cleaning javascript tags when saving in the database
    // public function setBodyAttribute($value)
    // {
    //     $this->attributes['body'] = clean($value);
    // }

    public function getUrlAttribute()
    {
        return route('questions.show', $this->slug);
    }

    public function getCreatedDateAttribute()
    {
        return $this->created_at->diffForHumans();
    }

    public function getStatusAttribute()
    {
        if ($this->answer_count > 0) {
            if ($this->best_answer_id) {
                return "answered-accepted";
            }
            return "answer";
        }
        return "unanswered";
    }

    public function getBodyHtmlAttribute()
    {
        return clean($this->bodyHtml());
    }

    public function getIsFavoritedAttribute()
    {
        return $this->isFavorited();
    }
    
    public function getFavoriteCountAttribute()
    {
        return $this->favorites->count();
    }
    
    public function getExcerptAttribute()
    {
        return $this->excerpt(250);
    }
    
    public function acceptBestAnswer(Answer $answer)
    {
        $this->best_answer_id = $answer->id;
        $this->save();
    }

    public function isFavorited()
    {
        return $this->favorites()->where('user_id', auth()->id())->count() > 0;
    }

    private function bodyHtml()
    {
        return \Parsedown::instance()->text($this->body);
    }

    private function excerpt($length)
    {
        return str_limit(strip_tags($this->bodyHtml()), $length);
    }
}

app/User.php
<?php

namespace App;

use App\Question;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function questions()
    {
        return $this->hasMany(Question::class);
    }

    public function answers()
    {
        return $this->hasMany(Answer::class);
    }

    public function favorites()
    {
        return $this->belongsToMany(Question::class, 'favorites')->withTimestamps(); //, 'user_id', 'question_id');
    }

    public function voteQuestions()
    {
        return $this->morphedByMany(Question::class, 'votable')->withTimestamps();
    }

    public function voteAnswers()
    {
        return $this->morphedByMany(Answer::class, 'votable')->withTimestamps();
    }

    public function getUrlAttribute()
    {
        // return route('questions.show', $this->id);
        return "#";
    }

    public function getAvatarAttribute()
    {
        $email = $this->email;
        $size = 32;

        return "https://www.gravatar.com/avatar/" . md5( strtolower( trim( $email ) ) ) . "?s=" . $size;
    }

    public function voteQuestion(Question $question, $vote)
    {
        $voteQuestions = $this->voteQuestions();
        $this->_vote($voteQuestions, $question, $vote);
    }

    public function voteAnswer(Answer $answer, $vote)
    {
        $voteAnswers = $this->voteAnswers();
        $this->_vote($voteAnswers, $answer, $vote);
    }

    private function _vote($relationship, $model, $vote)
    {
        if ($relationship->where('votable_id', $model->id)->exists()) {
            $relationship->updateExistingPivot($model, ['vote' => $vote]);
        } else {
            $relationship->attach($model, ['vote' => $vote]);
        }
        $model->load('votes');
        $downVotes = (int) $model->downVotes()->sum('vote');
        $upVotes = (int) $model->upVotes()->sum('vote');
        
        $model->vote_count = $upVotes + $downVotes;
        $model->save();
    }
}

resources/views/shared/_accept.blade.php
{{-- BEST ANSWER --}}
@can('accept', $model)
    <a href="#" title="Mark this answer as best answer" 
        class="{{ $model->status }} mt-2"
        onclick="event.preventDefault(); document.getElementById('accept-answer-{{ $model->id }}').submit();"
        >
        <i class="fas fa-check fa-2x"></i>
    </a>
    <form action="{{ route('answers.accept', $model->id) }}" method="POST" id="accept-answer-{{ $model->id }}" style="display:none;">
        @csrf
    </form>
@else
    @if ($model->is_best)
        <a href="#" title="The question owner accepted this answer as best answer" 
            class="{{ $model->status }} mt-2"
            >
            <i class="fas fa-check fa-2x"></i>
        </a>
    @endif
@endcan

resources/views/shared/_author.blade.php
<span class="text-muted">{{ $label . " " . $model->created_date }}</span>
<div class="media mt-2">
    <a href="{{ $model->user->url }}" class="pr-2">
        <img src="{{ $model->user->avatar }}">
    </a>
    <div class="media-body mt-1">
        <a href="{{ $model->user->url }}">{{ $model->user->name }}</a>
    </div>
</div>

resources/views/shared/_favorite.blade.php
{{-- FAVORITES --}}
<a href="#" title="Click to mark as favorite question (Click again to undo)" 
    class="favorite mt-2 {{ Auth::guest() ? 'off' : ($model->is_favorited ? 'favorited' : '') }}"
    onclick="event.preventDefault(); document.getElementById('favorite-question-{{ $model->id }}').submit();"
    >
    <i class="fas fa-star fa-2x"></i>
    <span class="favorites-count">{{ $model->favorite_count }}</span>
</a>
<form action="/questions/{{ $model->id }}/favorites" method="POST" id="favorite-question-{{ $model->id }}" style="display:none;">
    @csrf
    @if ($model->is_favorited)
        @method ('DELETE')
    @endif
</form>

resources/views/shared/_vote.blade.php
@if ($model instanceof App\Question)
    @php
        $name = 'question';
        $firstURISegment = 'questions';
    @endphp
@elseif ($model instanceof App\Answer)
    @php
        $name = 'answer';
        $firstURISegment = 'answers';
    @endphp
@endif

@php
    $formId = $name . "-" . $model->id;
    $formAction = "/{$firstURISegment}/{$model->id}/vote";
@endphp
<div class="d-flex flex-column vote-controls">
    {{-- VOTE UP --}}
    <a href="#" title="This {{ $name }} is useful" 
        class="vote-up {{ Auth::guest() ? 'off' : '' }}"
        onclick="event.preventDefault(); document.getElementById('up-vote-{{ $formId }}').submit();"
        >
        <i class="fas fa-caret-up fa-3x"></i>
    </a>
    <form action="{{ $formAction }}" method="POST" id="up-vote-{{ $formId }}" style="display:none;">
        @csrf
        <input type="hidden" name="vote" value="1">
    </form>

    {{-- VOTE COUNT --}}
    <span class="votes-count">{{ $model->vote_count }}</span>

    {{-- VOTE DOWN --}}
    <a href="#" title="This {{ $name }} is not useful" 
        class="vote-down {{ Auth::guest() ? 'off' : '' }}"
        onclick="event.preventDefault(); document.getElementById('down-vote-{{ $formId }}').submit();"
        >
        <i class="fas fa-caret-down fa-3x"></i>
    </a>
    <form action="{{ $formAction }}" method="POST" id="down-vote-{{ $formId }}" style="display:none;">
        @csrf
        <input type="hidden" name="vote" value="-1">
    </form>

    @if ($model instanceof App\Question)
        @include('shared._favorite', [
            'model' => $model
        ])
    @elseif ($model instanceof App\Answer)
        @include('shared._accept', [
            'model' => $model
        ])
    @endif
</div>